### ISSUE TITLE
windows 系统作为本地使用时会传不上去，远程路径解析错误。

### ISSUE THREAD

**Issue by zhaoguoweiLLHC** [wang-jun-coder/wj-publish#1]
![eaa30766f25a5946acbea8dfcbe3aec](https://user-images.githubusercontent.com/23580548/69772663-8b38a500-11cb-11ea-8ee9-2d8848a9c86f.png)
远程是linux服务器

**Comment by zhaoguoweiLLHC** [comment]
![a2669d9e01c7e6962cc3c6eaa149331](https://user-images.githubusercontent.com/23580548/69780204-884aae00-11e5-11ea-8e01-cc0abacd1982.png)
自己改动后修复。

**Comment by wang-jun-coder** [comment]
@zhaoguoweiLLHC 欢迎 pr, 我测试后可重新发版, 免得手动改了

**Comment by zhaoguoweiLLHC** [comment]
@wang-jun-coder ok，我pr。
